name: applestore
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/imagess.png
    - assets/storeperson.png
    - assets/store-card-50-specialist-help-202309.jpeg
    - assets/ipad-card-40-education-202108.jpeg
    - assets/store-card-13-accessories-nav-202309.png
    - assets/store-card-13-airpods-nav-202209.png
    - assets/store-card-13-airtags-nav-202108.png
    - assets/store-card-13-appletv-nav-202210.png
    - assets/store-card-13-homepod-nav-202301.png
    - assets/store-card-13-ipad-nav-202210.png
    - assets/store-card-13-iphone-nav-202309_GEO_US.png
    - assets/store-card-13-mac-nav-202310.png
    - assets/store-card-13-vision-pro-nav-202401.png
    - assets/store-card-13-watch-nav-202309.png
    - assets/applestoress.png

  # fonts:
  #   - family: SFPro
  #     fonts:
  #       - asset: fonts/SF-Pro-Text-Regular.otf
  #       - asset: fonts/SF-Pro-Text-Bold.otf
